-- local config = {
-- 	cmd = {
-- 		"/home/java25/.local/share/nvim/mason/bin/jdtls -configuration /home/java25/.cache/jdtls/config -data /home/java25/.cache/jdtls/workspace",
-- 	},
-- 	root_dir = vim.fs.dirname(vim.fs.find({ "gradlew", ".git", "mvnw" }, { upward = true })[1]),
-- }
-- require("jdtls").start_or_attach(config)
